#!/bin/bash

# bar_battery () {
# 	if [ -e /sys/class/power_supply/BAT1/capacity ]; then
# 		CHARGE=$(cat /sys/class/power_supply/BAT1/capacity)
# 		STATUS=$(cat /sys/class/power_supply/BAT1/status)
# 		printf "%s, %s%% | " "$STATUS" "$CHARGE"
# 	fi
# }

while true; do
	xsetroot -name "$(date "+%H:%M %D")"
	sleep 30
done
